# CMake generated Testfile for 
# Source directory: C:/ITKSNAP/itk-snap-src
# Build directory: C:/ITKSNAP/itk-snap- bin
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BasicSlicingTestX39 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/X39.nii.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X39.nii.gz" "C:/ITKSNAP/itk-snap- bin/Debug/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/MRIcrop-seg.gipl.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X39.nii.gz" "X" "39" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(BasicSlicingTestX39 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/X39.nii.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X39.nii.gz" "C:/ITKSNAP/itk-snap- bin/Release/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/MRIcrop-seg.gipl.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X39.nii.gz" "X" "39" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(BasicSlicingTestX39 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/X39.nii.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X39.nii.gz" "C:/ITKSNAP/itk-snap- bin/MinSizeRel/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/MRIcrop-seg.gipl.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X39.nii.gz" "X" "39" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(BasicSlicingTestX39 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/X39.nii.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X39.nii.gz" "C:/ITKSNAP/itk-snap- bin/RelWithDebInfo/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/MRIcrop-seg.gipl.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X39.nii.gz" "X" "39" "irisRLE")
else()
  add_test(BasicSlicingTestX39 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BasicSlicingTestY55 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Y55.nii.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y55.nii.gz" "C:/ITKSNAP/itk-snap- bin/Debug/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/MRIcrop-seg.gipl.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y55.nii.gz" "Y" "55" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(BasicSlicingTestY55 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Y55.nii.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y55.nii.gz" "C:/ITKSNAP/itk-snap- bin/Release/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/MRIcrop-seg.gipl.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y55.nii.gz" "Y" "55" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(BasicSlicingTestY55 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Y55.nii.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y55.nii.gz" "C:/ITKSNAP/itk-snap- bin/MinSizeRel/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/MRIcrop-seg.gipl.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y55.nii.gz" "Y" "55" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(BasicSlicingTestY55 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Y55.nii.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y55.nii.gz" "C:/ITKSNAP/itk-snap- bin/RelWithDebInfo/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/MRIcrop-seg.gipl.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y55.nii.gz" "Y" "55" "irisRLE")
else()
  add_test(BasicSlicingTestY55 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BasicSlicingTestZ32 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Z32.nii.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z32.nii.gz" "C:/ITKSNAP/itk-snap- bin/Debug/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/MRIcrop-seg.gipl.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z32.nii.gz" "Z" "32" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(BasicSlicingTestZ32 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Z32.nii.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z32.nii.gz" "C:/ITKSNAP/itk-snap- bin/Release/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/MRIcrop-seg.gipl.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z32.nii.gz" "Z" "32" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(BasicSlicingTestZ32 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Z32.nii.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z32.nii.gz" "C:/ITKSNAP/itk-snap- bin/MinSizeRel/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/MRIcrop-seg.gipl.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z32.nii.gz" "Z" "32" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(BasicSlicingTestZ32 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Z32.nii.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z32.nii.gz" "C:/ITKSNAP/itk-snap- bin/RelWithDebInfo/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/MRIcrop-seg.gipl.gz" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z32.nii.gz" "Z" "32" "irisRLE")
else()
  add_test(BasicSlicingTestZ32 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SlicingPerformanceTestX300 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/X300.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X300.mha" "C:/ITKSNAP/itk-snap- bin/Debug/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/vb-seg.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X300.mha" "X" "300" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SlicingPerformanceTestX300 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/X300.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X300.mha" "C:/ITKSNAP/itk-snap- bin/Release/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/vb-seg.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X300.mha" "X" "300" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SlicingPerformanceTestX300 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/X300.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X300.mha" "C:/ITKSNAP/itk-snap- bin/MinSizeRel/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/vb-seg.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X300.mha" "X" "300" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SlicingPerformanceTestX300 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/X300.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X300.mha" "C:/ITKSNAP/itk-snap- bin/RelWithDebInfo/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/vb-seg.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/X300.mha" "X" "300" "irisRLE")
else()
  add_test(SlicingPerformanceTestX300 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SlicingPerformanceTestY300 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Y300.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y300.mha" "C:/ITKSNAP/itk-snap- bin/Debug/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/vb-seg.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y300.mha" "Y" "300" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SlicingPerformanceTestY300 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Y300.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y300.mha" "C:/ITKSNAP/itk-snap- bin/Release/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/vb-seg.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y300.mha" "Y" "300" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SlicingPerformanceTestY300 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Y300.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y300.mha" "C:/ITKSNAP/itk-snap- bin/MinSizeRel/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/vb-seg.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y300.mha" "Y" "300" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SlicingPerformanceTestY300 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Y300.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y300.mha" "C:/ITKSNAP/itk-snap- bin/RelWithDebInfo/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/vb-seg.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Y300.mha" "Y" "300" "irisRLE")
else()
  add_test(SlicingPerformanceTestY300 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SlicingPerformanceTestZ150 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Z150.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z150.mha" "C:/ITKSNAP/itk-snap- bin/Debug/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/vb-seg.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z150.mha" "Z" "150" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SlicingPerformanceTestZ150 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Z150.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z150.mha" "C:/ITKSNAP/itk-snap- bin/Release/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/vb-seg.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z150.mha" "Z" "150" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SlicingPerformanceTestZ150 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Z150.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z150.mha" "C:/ITKSNAP/itk-snap- bin/MinSizeRel/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/vb-seg.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z150.mha" "Z" "150" "irisRLE")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SlicingPerformanceTestZ150 "C:/Program Files/ITK/bin/itkTestDriver.exe" "--compare" "C:/ITKSNAP/itk-snap-src/Testing/TestData/Z150.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z150.mha" "C:/ITKSNAP/itk-snap- bin/RelWithDebInfo/SlicingPerformanceTest.exe" "C:/ITKSNAP/itk-snap-src/Testing/TestData/vb-seg.mha" "C:/ITKSNAP/itk-snap- bin/Testing/Temporary/Z150.mha" "Z" "150" "irisRLE")
else()
  add_test(SlicingPerformanceTestZ150 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(IRISApplicationTest "C:/ITKSNAP/itk-snap- bin/Debug/logic_api_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(IRISApplicationTest "C:/ITKSNAP/itk-snap- bin/Release/logic_api_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(IRISApplicationTest "C:/ITKSNAP/itk-snap- bin/MinSizeRel/logic_api_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(IRISApplicationTest "C:/ITKSNAP/itk-snap- bin/RelWithDebInfo/logic_api_test.exe")
else()
  add_test(IRISApplicationTest NOT_AVAILABLE)
endif()
add_test(Workspace "ITK-SNAP" "--test" "Workspace" "--testacc" "1.0" "--testdir" "C:/ITKSNAP/itk-snap-src/Testing/TestData")
set_tests_properties(Workspace PROPERTIES  ENVIRONMENT "PATH=C:\\Qt\\Qt5.6.2\\5.6\\msvc2015_64\\bin" TIMEOUT "180")
add_test(DiffSpace "ITK-SNAP" "--test" "DiffSpace" "--testacc" "1.0" "--testdir" "C:/ITKSNAP/itk-snap-src/Testing/TestData")
set_tests_properties(DiffSpace PROPERTIES  ENVIRONMENT "PATH=C:\\Qt\\Qt5.6.2\\5.6\\msvc2015_64\\bin" TIMEOUT "180")
add_test(ProbeIntensity "ITK-SNAP" "--test" "ProbeIntensity" "--testacc" "1.0" "--testdir" "C:/ITKSNAP/itk-snap-src/Testing/TestData")
set_tests_properties(ProbeIntensity PROPERTIES  ENVIRONMENT "PATH=C:\\Qt\\Qt5.6.2\\5.6\\msvc2015_64\\bin" TIMEOUT "180")
add_test(RegionCompetition "ITK-SNAP" "--test" "RegionCompetition" "--testacc" "1.0" "--testdir" "C:/ITKSNAP/itk-snap-src/Testing/TestData")
set_tests_properties(RegionCompetition PROPERTIES  ENVIRONMENT "PATH=C:\\Qt\\Qt5.6.2\\5.6\\msvc2015_64\\bin" TIMEOUT "180")
add_test(RandomForest "ITK-SNAP" "--test" "RandomForest" "--testacc" "1.0" "--testdir" "C:/ITKSNAP/itk-snap-src/Testing/TestData")
set_tests_properties(RandomForest PROPERTIES  ENVIRONMENT "PATH=C:\\Qt\\Qt5.6.2\\5.6\\msvc2015_64\\bin" TIMEOUT "180")
add_test(RandomForestBailOut "ITK-SNAP" "--test" "RandomForestBailOut" "--testacc" "1.0" "--testdir" "C:/ITKSNAP/itk-snap-src/Testing/TestData")
set_tests_properties(RandomForestBailOut PROPERTIES  ENVIRONMENT "PATH=C:\\Qt\\Qt5.6.2\\5.6\\msvc2015_64\\bin" TIMEOUT "180")
subdirs("Submodules/c3d")
subdirs("Submodules/greedy")
subdirs("Utilities/Workspace")
